"""
Automatic Alert Service for F.A.R.O.
Generates alerts for suspicious route recurrences and pattern anomalies.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional
from uuid import UUID

from sqlalchemy import and_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.base import (
    SuspicionReport,
    Unit,
    UnitType,
    Agency,
    AgencyType,
)
from app.services.route_prediction_service import (
    get_pattern_drift_alert,
    get_recurring_route_alerts,
)
from app.services.suspicious_route_service import check_route_match, SuspiciousRouteMatchRequest
from app.schemas.common import GeolocationPoint


@dataclass
class Alert:
    """Automatic alert generated by the system."""
    alert_type: str  # suspicious_route_match, pattern_drift, recurring_route
    plate_number: str
    severity: str  # low, medium, high, critical
    confidence: float
    details: dict
    triggered_at: datetime
    requires_review: bool
    targets: List[str] = field(default_factory=lambda: ["mobile_agents"])


async def get_active_agents_near(
    db: AsyncSession, location: GeolocationPoint, radius_km: float = 2.0
) -> List[User]:
    """Find agents on duty near a specific location."""
    # Convert location to PostGIS point
    point = f"SRID=4326;POINT({location.longitude} {location.latitude})"
    
    query = (
        select(User)
        .where(
            and_(
                User.role == UserRole.FIELD_AGENT,
                User.is_on_duty == True,
                User.service_expires_at > datetime.utcnow(),
                func.ST_DWithin(
                    User.last_known_location,
                    point,
                    radius_km / 111.32,  # Rough degrees conversion for 4326
                ),
            )
        )
    )
    result = await db.execute(query)
    return result.scalars().all()


async def get_alert_context(db: AsyncSession, agency_id: UUID, agent_id: Optional[UUID] = None) -> dict:
    """Determine radius and dispatch targets based on unit context."""
    if not agent_id:
        return {"radius_km": 2.0, "context": "urban", "targets": ["mobile_agents"]}
    
    # Get reporting unit
    query = select(Unit).join(User, User.unit_id == Unit.id).where(User.id == agent_id)
    unit = (await db.execute(query)).scalar_one_or_none()
    
    if unit and unit.unit_type == UnitType.HIGHWAY:
        return {
            "radius_km": 15.0, 
            "context": "highway", 
            "targets": ["ali_console", "ari_node"]
        }
    
    return {
        "radius_km": 2.0, 
        "context": "urban", 
        "targets": ["mobile_agents"]
    }


async def check_observation_alerts(
    db: AsyncSession,
    observation_id: UUID,
    plate_number: str,
    location: GeolocationPoint,
    observed_at: datetime,
    agency_id: UUID,
    agent_id: Optional[UUID] = None,
) -> List[Alert]:
    """
    Check all alert conditions for a new observation.
    Returns list of triggered alerts with contextual metadata.
    """
    alerts = []
    
    # Get contextual settings (Highway vs City)
    ctx = await get_alert_context(db, agency_id, agent_id)
    
    # 1. Check if observation matches any suspicious route
    match_request = SuspiciousRouteMatchRequest(
        observation_id=observation_id,
        plate_number=plate_number,
        location=location,
        observed_at=observed_at,
        search_radius_km=ctx["radius_km"], # Pass the contextual radius
    )
    
    match_result = await check_route_match(db, match_request, agency_id)
    
    if match_result.alert_triggered:
        # Determine severity
        max_risk = "low"
        for route in match_result.matched_routes:
            if route["risk_level"] == "critical":
                max_risk = "critical"
                break
            elif route["risk_level"] == "high" and max_risk != "critical":
                max_risk = "high"
        
        alerts.append(Alert(
            alert_type="suspicious_route_match",
            plate_number=plate_number,
            severity=max_risk,
            confidence=0.9,
            details={
                "matched_routes": match_result.matched_routes,
                "distance_meters": match_result.distance_meters,
                "operational_context": ctx["context"],
                "dispatch_targets": ctx["targets"],
            },
            triggered_at=datetime.utcnow(),
            requires_review=True,
        ))
    
    # 2. Check for pattern drift
    drift_alert = await get_pattern_drift_alert(db, plate_number, agency_id)
    if drift_alert:
        alerts.append(Alert(
            alert_type="pattern_drift",
            plate_number=plate_number,
            severity="medium",
            confidence=drift_alert.get("drift_percent", 0) / 100.0,
            details={
                **drift_alert,
                "operational_context": ctx["context"],
                "dispatch_targets": ctx["targets"],
            },
            triggered_at=datetime.utcnow(),
            requires_review=True,
        ))
    
    return alerts


async def get_recurring_route_alerts_for_agency(
    db: AsyncSession,
    agency_id: UUID,
    min_recurrence_score: float = 0.7,
    min_pattern_strength: float = 0.6,
) -> List[Alert]:
    """
    Get alerts for plates with strong recurring route patterns.
    """
    recurring_alerts = await get_recurring_route_alerts(
        db, agency_id, min_recurrence_score, min_pattern_strength
    )
    
    alerts = []
    for alert_data in recurring_alerts:
        # Determine severity based on recurrence and pattern strength
        recurrence = alert_data["recurrence_score"]
        strength = alert_data["pattern_strength"]
        
        if recurrence > 0.9 and strength > 0.8:
            severity = "high"
        elif recurrence > 0.8 and strength > 0.7:
            severity = "medium"
        else:
            severity = "low"
        
        alerts.append(Alert(
            alert_type="recurring_route",
            plate_number=alert_data["plate_number"],
            severity=severity,
            confidence=(recurrence + strength) / 2,
            details=alert_data,
            triggered_at=datetime.utcnow(),
            requires_review=True,
        ))
    
    return alerts


async def check_suspicious_route_recurrence_alerts(
    db: AsyncSession,
    agency_id: UUID,
    hours: int = 24,
) -> List[Alert]:
    """
    Check for plates that have matched suspicious routes multiple times recently.
    """
    # Get observations from the last N hours
    from datetime import timedelta
    
    cutoff_time = datetime.utcnow() - timedelta(hours=hours)
    
    # This would require a dedicated table to track route matches
    # For now, we'll implement a simplified version by checking recent observations
    # against all active suspicious routes
    
    # Get all active approved suspicious routes
    query = select(SuspiciousRoute).where(
        and_(
            SuspiciousRoute.agency_id == agency_id,
            SuspiciousRoute.is_active == True,
            SuspiciousRoute.approval_status == "approved",
        )
    )
    
    routes = (await db.execute(query)).scalars().all()
    
    if not routes:
        return []
    
    # Get recent observations
    obs_query = select(VehicleObservation).where(
        and_(
            VehicleObservation.agency_id == agency_id,
            VehicleObservation.observed_at_local >= cutoff_time,
        )
    )
    
    observations = (await db.execute(obs_query)).scalars().all()
    
    # Count matches per plate
    from collections import defaultdict
    plate_match_counts = defaultdict(int)
    plate_route_matches = defaultdict(list)
    
    for obs in observations:
        match_request = SuspiciousRouteMatchRequest(
            observation_id=obs.id,
            plate_number=obs.plate_number,
            location=GeolocationPoint(
                latitude=to_shape(obs.location).y,
                longitude=to_shape(obs.location).x,
            ),
            observed_at=obs.observed_at_local,
        )
        
        match_result = await check_route_match(db, match_request, agency_id)
        if match_result.alert_triggered:
            plate_match_counts[obs.plate_number] += 1
            plate_route_matches[obs.plate_number].extend(match_result.matched_routes)
    
    # Generate alerts for plates with multiple matches
    alerts = []
    for plate, count in plate_match_counts.items():
        if count >= 3:  # Alert if 3+ matches in period
            alerts.append(Alert(
                alert_type="suspicious_route_recurrence",
                plate_number=plate,
                severity="high" if count >= 5 else "medium",
                confidence=min(1.0, count / 5.0),
                details={
                    "match_count": count,
                    "period_hours": hours,
                    "matched_routes": plate_route_matches[plate],
                },
                triggered_at=datetime.utcnow(),
                requires_review=True,
            ))
    
    return alerts


async def get_aggregated_alerts(
    db: AsyncSession,
    agency_id: UUID,
    alert_type: Optional[str] = None,
    severity: Optional[str] = None,
    limit: int = 100,
) -> dict:
    """
    Get aggregated alert summary for the agency.
    """
    # Get all types of alerts
    all_alerts = []
    
    # Recurring route alerts
    recurring = await get_recurring_route_alerts_for_agency(db, agency_id)
    all_alerts.extend(recurring)
    
    # Suspicious route recurrence alerts (last 24h)
    recurrence = await check_suspicious_route_recurrence_alerts(db, agency_id)
    all_alerts.extend(recurrence)
    
    # Filter by type and severity if specified
    if alert_type:
        all_alerts = [a for a in all_alerts if a.alert_type == alert_type]
    if severity:
        all_alerts = [a for a in all_alerts if a.severity == severity]
    
    # Sort by severity and confidence
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    all_alerts.sort(key=lambda a: (severity_order.get(a.severity, 4), -a.confidence))
    
    return {
        "total_alerts": len(all_alerts),
        "alerts": [
            {
                "alert_type": a.alert_type,
                "plate_number": a.plate_number,
                "severity": a.severity,
                "confidence": a.confidence,
                "details": a.details,
                "triggered_at": a.triggered_at.isoformat(),
                "requires_review": a.requires_review,
            }
            for a in all_alerts[:limit]
        ],
        "summary": {
            "critical": len([a for a in all_alerts if a.severity == "critical"]),
            "high": len([a for a in all_alerts if a.severity == "high"]),
            "medium": len([a for a in all_alerts if a.severity == "medium"]),
            "low": len([a for a in all_alerts if a.severity == "low"]),
        },
    }
