"""add_approach_fields_to_watchlist

Revision ID: 76d0a9704880
Revises: 0024_table_partitioning
Create Date: 2026-04-26 20:18:33.351458
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76d0a9704880'
down_revision = '0024_table_partitioning'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the new approach fields to watchlistentry
    op.add_column('watchlistentry', sa.Column('requires_approach', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('watchlistentry', sa.Column('approach_guidance', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlistentry', 'approach_guidance')
    op.drop_column('watchlistentry', 'requires_approach')
    # ### end Alembic commands ###
